import numpy as np
import itertools
from .. import Numputils as nput
from .. import Iterators as itut
from .Permutations import UniquePermutations, UniqueSubsets, IntegerPartitioner, IntegerPartitioner2D, lehmer_encode
__all__ = ['YoungTableauxGenerator']

class YoungTableauxGenerator:
    tableaxu_cache = {}
    subset_cache = {}

    def __init__(self, base_int, tableaxu_cache=None, subset_cache=None):
        """
        **LLM Docstring**

        Initialize a standard Young-tableau generator and its caches.

        When explicit caches are not supplied, the class-level tableau and subset caches are reused across instances.

        :param base_int: integer whose partitions define the tableau sizes generated by this instance
        :type base_int: int
        :param tableaxu_cache: optional mapping from partition tuples to cached tableau arrays
        :type tableaxu_cache: dict | None
        :param subset_cache: optional mapping from partition-size tuples to cached unique subsets
        :type subset_cache: dict | None
        :return: `None`
        :rtype: None
        """
        ...

    def number_of_tableaux(self, partitions=None, **partition_opts):
        """
        **LLM Docstring**

        Count standard Young tableaux over one or more partitions of the instance base.

        If `partitions` is omitted, integer partitions of `self.base` are generated. A single partition is wrapped, while nested partition groups are flattened before summing the hook-length counts.

        :param partitions: a single partition, a flat collection of partitions, or nested partition groups
        :type partitions: array-like | None
        :param partition_opts: options forwarded to `IntegerPartitioner.partitions` when partitions are generated
        :type partition_opts: Any
        :return: total number of standard tableaux for all selected partitions
        :rtype: int
        """
        ...

    def get_standard_tableaux(self, partitions=None, *, symbols=None, brute_force=False, return_partitions=False, **partition_opts):
        """
        **LLM Docstring**

        Generate standard Young tableaux for selected partitions.

        The method normalizes single, flat, and nested partition inputs, then delegates each partition to `standard_partition_tableaux`. When requested, it returns the normalized partitions alongside the generated row-array representation.

        :param partitions: a single partition, flat partition collection, or nested partition groups; defaults to partitions of `self.base`
        :type partitions: array-like | None
        :param symbols: optional values used to replace the default integer labels by indexed lookup
        :type symbols: array-like | None
        :param brute_force: use permutation filtering instead of the recursive construction
        :type brute_force: bool
        :param return_partitions: return the normalized partition specification with the tableaux
        :type return_partitions: bool
        :param partition_opts: options forwarded to `IntegerPartitioner.partitions`
        :type partition_opts: Any
        :return: generated tableau arrays, optionally paired with their partitions
        :rtype: list[numpy.ndarray] | tuple[list[numpy.ndarray], array-like]
        """
        ...

    @classmethod
    def standard_partition_tableaux_bf(cls, partition, unique_perms=False, concatenate=False):
        """
        **LLM Docstring**

        Enumerate tableaux for a partition by brute-force permutation filtering.

        Rows are represented as separate arrays whose first axis indexes candidate tableaux. Candidates are retained only when every row and every transposed column is nondecreasing. With `unique_perms=True`, row-membership permutations are used to derive rank positions; otherwise all permutation indices of `sum(partition)` are considered.

        :param partition: row lengths of the Young diagram
        :type partition: sequence[int]
        :param unique_perms: derive candidates from unique permutations of repeated row labels
        :type unique_perms: bool
        :param concatenate: concatenate row arrays along the column axis before returning
        :type concatenate: bool
        :return: filtered tableau rows or their concatenation
        :rtype: list[numpy.ndarray] | numpy.ndarray
        """
        ...

    @classmethod
    def populate_sst_frames(cls, partition, frame, segment_lists):
        """
        **LLM Docstring**

        Fill tableau frame shapes from segmented symbol selections.

        For each entry in `segment_lists`, the function allocates one integer row per partition row and copies successive slices from each segment according to the counts stored in `frame`. Segment offsets are tracked independently for each segment index.

        :param partition: row lengths used to allocate each output subframe
        :type partition: sequence[int]
        :param frame: per-row counts describing how many values to take from each segment
        :type frame: sequence[sequence[int]]
        :param segment_lists: iterable of segment collections supplying the values
        :type segment_lists: iterable[sequence[array-like]]
        :return: list of populated subframes, each represented as a list of row arrays
        :rtype: list[list[numpy.ndarray]]
        """
        ...

    @classmethod
    def standard_partitions(cls, partition):
        """
        **LLM Docstring**

        Generate valid two-dimensional partition frames and cumulative offsets.

        `IntegerPartitioner2D.get_partitions` constructs candidate arrays. Candidates are retained when cumulative offsets are nonincreasing down every column.

        :param partition: one-dimensional partition used as both source and target dimensions
        :type partition: sequence[int]
        :return: valid partition frames and their cumulative offsets
        :rtype: list[numpy.ndarray]
        """
        ...

    @classmethod
    def hook_numbers(cls, partition):
        """
        **LLM Docstring**

        Compute hook lengths for every cell of a Young diagram.

        Cells are traversed row by row. Each hook length is the number of cells from the current position through the end of its row plus one for every lower row extending into the same column.

        :param partition: row lengths of the Young diagram
        :type partition: sequence[int]
        :return: hook lengths in row-major order
        :rtype: list[int]
        """
        ...

    @classmethod
    def count_standard_tableaux(cls, partition):
        """
        **LLM Docstring**

        Count standard tableaux using the hook-length formula.

        The function computes `n! / product(hooks)` as a product of elementwise ratios, rounds the floating-point result, and converts it to an integer NumPy scalar.

        :param partition: row lengths of the Young diagram
        :type partition: sequence[int]
        :return: number of standard Young tableaux of the given shape
        :rtype: numpy.integer
        """
        ...

    @classmethod
    def split_frame(cls, partition, offsets):
        """
        **LLM Docstring**

        Split a partition frame into one-row components with aligned offsets.

        Each nonzero row contributes a pair of length-`len(partition)` vectors: one containing only that row's size and one containing only its offset, both padded with zeros elsewhere.

        :param partition: per-row sizes for the frame
        :type partition: sequence[int]
        :param offsets: per-row starting offsets
        :type offsets: sequence[int]
        :return: list of `[size_vector, offset_vector]` pairs for nonzero rows
        :rtype: list[list[numpy.ndarray]]
        """
        ...

    @classmethod
    def _sst_2(cls, partition, cache=None, subset_cache=None, symbols=None):
        """
        **LLM Docstring**

        Recursively construct standard tableaux for one partition.

        Small partitions are handled by explicit arrays. Larger partitions are decomposed into valid two-dimensional frames, unique symbol subsets are assigned to frame components, and recursive tableaux are combined. Candidate rows are filtered for cross-row ordering, completeness, and duplicate Lehmer codes before being cached under the partition tuple. The cached representation is a list of row arrays with shape `(n_tableaux, row_length)`.

        :param partition: row lengths of the target Young diagram
        :type partition: sequence[int]
        :param cache: optional tableau cache keyed by partition tuples
        :type cache: dict | None
        :param subset_cache: optional unique-subset cache keyed by component-size tuples
        :type subset_cache: dict | None
        :param symbols: optional labels to place in the tableaux instead of `0..sum(partition)-1`
        :type symbols: array-like | None
        :return: one array per tableau row, each containing all generated tableaux along axis 0
        :rtype: list[numpy.ndarray]
        """
        ...

    @classmethod
    def standard_partition_tableaux(cls, partition, cache=None, subset_cache=None, symbols=None, brute_force=False):
        """
        **LLM Docstring**

        Generate all standard tableaux for a single partition.

        The method selects either brute-force permutation filtering or the recursive `_sst_2` implementation. If `symbols` is provided, each integer index in every row array is replaced by the corresponding symbol.

        :param partition: row lengths of the Young diagram
        :type partition: sequence[int]
        :param cache: optional recursive tableau cache
        :type cache: dict | None
        :param subset_cache: optional unique-subset cache
        :type subset_cache: dict | None
        :param symbols: optional label array indexed by generated tableau entries
        :type symbols: array-like | None
        :param brute_force: use `standard_partition_tableaux_bf` instead of `_sst_2`
        :type brute_force: bool
        :return: list of row arrays with the tableau index along axis 0
        :rtype: list[numpy.ndarray]
        """
        ...

    @classmethod
    def print_tableaux(cls, tableaux):
        """
        **LLM Docstring**

        Format and print one or more tableau collections.

        A raw row-array collection is wrapped as a single collection. Rows are zipped by tableau index, formatted with `TableFormatter`, and preceded by a horizontal separator matching the first rendered line width.

        :param tableaux: tableau row arrays or a list of such collections
        :type tableaux: list[numpy.ndarray] | list[list[numpy.ndarray]]
        :return: `None`; output is written to standard output
        :rtype: None
        """
        ...