name: McUtils
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy
  - matplotlib
  - h5py
  - ipywidgets
variables:
  - PYTHONPATH: /home/jovyan
  - V2: asdasd
  - V3: asdasd